version: "3.8"

services:
   devops_nginx:
      build:
         context: ./nginx
         dockerfile: Dockerfile
      restart: unless-stopped
      ports:
         - "80:80"
      volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
         - client
         - strapi
      networks:
         - kindergarten_network

   client:
      build:
         context: ./client
         dockerfile: Dockerfile
      container_name: "client"
      restart: unless-stopped
      ports:
         - "3000:3000"
      networks:
         - kindergarten_network
         - strapi
      environment:
         CMS_API: http://16.171.254.90:1337
      depends_on:
         - strapi

   strapiDB:
      image: postgres:16-alpine
      container_name: "strapiDB"
      ports:
         - "5432:5432"
      environment:
         POSTGRES_DB: cms
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
      volumes:
         - ./cms_data/cms.sql:/docker-entrypoint-initdb.d/cms.sql
         - postgres-data:/var/lib/postgresql/data
      restart: unless-stopped
      user: "postgres"
      networks:
         - kindergarten_network
         - strapi

   strapi:
      container_name: strapi
      build:
         context: ./cms
         dockerfile: Dockerfile
      restart: unless-stopped
      env_file: ./cms/.env
      environment:
         STRAPI_ADMIN_BACKEND_URL: http://16.171.254.90:1337
         DATABASE_CLIENT: postgres
         DATABASE_PORT: 5432
         DATABASE_NAME: cms
         DATABASE_USERNAME: postgres
         DATABASE_PASSWORD: postgres
         DATABASE_HOST: strapiDB
         API_TOKEN_SALT: aMqqi4260qfhHxg3C8XXbw==
         TRANSFER_TOKEN_SALT: 2Mm2TehHXvdhoMUEc9XPaA==
         JWT_SECRET: oS2MxDtE+rso+P7/eOc9fQ==
         ADMIN_JWT_SECRET: elLC1QV1E8EKS4cXasbJnA==
         APP_KEYS: RD5i9SbFHgRU5fFAF4O89g==,0K9bkUDI2KDdlvDbf2Ybtw==,sDRo9OG0LVrd3p4dTKHcGg==,mi8PrTm+hxI29GmpQY9bGA==
         NODE_ENV: production
         HOST: strapi
         PORT: 1337
      volumes:
         - ./cms/config:/opt/app/config
         - ./cms/src:/opt/app/src
         - ./cms/package.json:/opt/package.json
         - ./cms/yarn.lock:/opt/yarn.lock
         - ./cms/.env:/opt/app/.env
         - ./cms/public/uploads:/opt/app/public/uploads
         - strapi-data:/opt/app/public/uploads
      ports:
         - "1337:1337"
      networks:
         - kindergarten_network
         - strapi
      depends_on:
         - strapiDB
volumes:
   strapi-data:
   postgres-data:

networks:
   kindergarten_network:
      driver: bridge
   strapi:
      driver: bridge
