export { default as HomePage } from './home/HomePage'
export { default as DocsPage } from './send-docs/DocsPage'
export { default as Parents } from './parent/Parents'
export { default as Gallery } from './gallery/GalleryServer'
export { default as Calendar } from './calendar/Calendar'
